tribits_package_define_dependencies(
  LIB_REQUIRED_PACKAGES MundyUtils MundyMath
  LIB_OPTIONAL_PACKAGES
  TEST_REQUIRED_PACKAGES
  TEST_OPTIONAL_PACKAGES
  LIB_REQUIRED_TPLS Kokkos OpenRAND fmt
  LIB_OPTIONAL_TPLS CUDA
  TEST_REQUIRED_TPLS
  TEST_OPTIONAL_TPLS GTest nanobench
)
