// @HEADER
// **********************************************************************************************************************
//
//                                          Mundy: Multi-body Nonlocal Dynamics
//                                              Copyright 2024 Bryce Palmer
//
// Developed under support from the NSF Graduate Research Fellowship Program.
//
// Mundy is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License
// as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
//
// Mundy is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty
// of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License along with Mundy. If not, see
// <https://www.gnu.org/licenses/>.
//
// **********************************************************************************************************************
// @HEADER

#ifndef MUNDY_MATH_CMATH_HPP_
#define MUNDY_MATH_CMATH_HPP_

/// \file cmath.hpp
/// \brief Math-function dispatch and scalar utilities compatible with auto-diff scalar types.
///
/// For arithmetic types the dispatch routes through Kokkos (device-compatible).
/// For all other types (AD duals, complex, ...) it uses `using std::func; func(x)` so that ADL
/// finds whatever overload the AD library provides in its own namespace.

// External
#include <Kokkos_Core.hpp>

// C++ core
#include <cmath>
#include <type_traits>

namespace mundy {

// ============================================================================
// passive_scalar — strip one AD layer to reach the underlying passive type
// ============================================================================

/// \brief Trait: underlying passive (non-AD) type of T.
/// For arithmetic T: `passive_scalar_t<T> == T`.
/// For AD types exposing `T::value_type`: `passive_scalar_t<T> == typename T::value_type`.
template <typename T>
struct passive_scalar {
  using type = T;
};

template <typename T>
  requires requires { typename T::value_type; }
struct passive_scalar<T> {
  using type = typename T::value_type;
};

template <typename T>
using passive_scalar_t = typename passive_scalar<T>::type;

// ============================================================================
// Kokkos numeric constants extended to AD scalar types
// ============================================================================

template <typename T>
inline constexpr auto mundy_infinity_v = Kokkos::Experimental::infinity_v<passive_scalar_t<T>>;

template <typename T>
inline constexpr auto mundy_epsilon_v = Kokkos::Experimental::epsilon_v<passive_scalar_t<T>>;

template <typename T>
inline constexpr auto mundy_norm_min_v = Kokkos::Experimental::norm_min_v<passive_scalar_t<T>>;

// ============================================================================
// Math dispatch — generated by two macros
// ============================================================================

/// Unary: arithmetic -> Kokkos::func(x); AD -> ADL + using std::func.
#define MUNDY_MATH_DISPATCH_UNARY(func)                    \
  template <typename T>                                    \
  KOKKOS_INLINE_FUNCTION constexpr auto func(const T& x) { \
    if constexpr (std::is_arithmetic_v<T>) {               \
      return Kokkos::func(x);                              \
    } else {                                               \
      using std::func;                                     \
      return func(x);                                      \
    }                                                      \
  }

/// Binary (possibly mixed types): arithmetic -> Kokkos::func(a,b); AD -> ADL + using std::func.
#define MUNDY_MATH_DISPATCH_BINARY(func)                               \
  template <typename T>                                                \
  KOKKOS_INLINE_FUNCTION constexpr auto func(const T& a, const T& b) { \
    if constexpr (std::is_arithmetic_v<T>) {                           \
      return Kokkos::func(a, b);                                       \
    } else {                                                           \
      using std::func;                                                 \
      return func(a, b);                                               \
    }                                                                  \
  }

MUNDY_MATH_DISPATCH_UNARY(sqrt)
MUNDY_MATH_DISPATCH_UNARY(cbrt)
MUNDY_MATH_DISPATCH_UNARY(sin)
MUNDY_MATH_DISPATCH_UNARY(cos)
MUNDY_MATH_DISPATCH_UNARY(tan)
MUNDY_MATH_DISPATCH_UNARY(asin)
MUNDY_MATH_DISPATCH_UNARY(acos)
MUNDY_MATH_DISPATCH_UNARY(atan)
MUNDY_MATH_DISPATCH_UNARY(exp)
MUNDY_MATH_DISPATCH_UNARY(log)
MUNDY_MATH_DISPATCH_UNARY(log10)
MUNDY_MATH_DISPATCH_UNARY(abs)
MUNDY_MATH_DISPATCH_UNARY(fabs)
MUNDY_MATH_DISPATCH_UNARY(floor)
MUNDY_MATH_DISPATCH_UNARY(ceil)
MUNDY_MATH_DISPATCH_UNARY(round)

MUNDY_MATH_DISPATCH_BINARY(atan2)
MUNDY_MATH_DISPATCH_BINARY(pow)
MUNDY_MATH_DISPATCH_BINARY(copysign)
MUNDY_MATH_DISPATCH_BINARY(min)
MUNDY_MATH_DISPATCH_BINARY(max)

#undef MUNDY_MATH_DISPATCH_UNARY
#undef MUNDY_MATH_DISPATCH_BINARY

}  // namespace mundy

#endif  // MUNDY_MATH_CMATH_HPP_
