from pathlib import Path

project = "MuNDy"
author = "Bryce Palmer"

docs_dir = Path(__file__).parent.resolve()
repo_root = docs_dir.parent
root_doc = "index"

extensions = [
    "myst_parser",
    "breathe",
    "exhale",
]

templates_path = ["_templates"]
exclude_patterns = [
    "_build",
    "Thumbs.db",
    ".DS_Store",
    "api",  # generated by Exhale
]

html_theme = "sphinx_rtd_theme"

myst_enable_extensions = [
    "colon_fence",
    "deflist",
    "fieldlist",
    "replacements",
    "smartquotes",
    "substitution",
    "tasklist",
]

primary_domain = "cpp"
highlight_language = "cpp"

breathe_projects = {
    "MuNDy": str(docs_dir / "xml"),
}
breathe_default_project = "MuNDy"

exhale_args = {
    "containmentFolder": "./api",
    "rootFileName": "library_root.rst",
    "rootFileTitle": "C++ API Reference",
    "doxygenStripFromPath": str(repo_root),
    "createTreeView": True,
    "exhaleExecutesDoxygen": False,
}