def cleanCheckout() {
  // noop - do nothing
  echo 'cleanCheckout() called - not yet implemented'
}

// pipeline {
//   agent any

//   stages {
//     stage('Validate repo') {
//       agent {
//         dockerfile {
//           filename 'ci/Dockerfile' // Can also be relative path to Dockerfile
//           dir '.'
//           label 'linux'
//           /* args '-X -Y' // These get passed to docker run */
//           /* additionalBuildArgs '-X -Y' // These get passed to docker build */
//         }
//       }
//       steps {
//         script {
//           cleanCheckout()
//         }
//       }
//       post { always { sh "rm -rf ./*" }}
//     }

//     stage('Build Software and Test Via Docker') {
//       agent {
//         dockerfile {
//           filename 'ci/Dockerfile' // Can also be relative path to Dockerfile
//           dir '.'
//           label 'linux'
//           /* args '-X -Y' // These get passed to docker run */
//           /* additionalBuildArgs '-X -Y' // These get passed to docker build */
//         }
//       }
//       steps {
//         echo 'Building software inside the container'
//         sh './scripts/build.sh'

//         echo 'Executing tests'
//         sh './scripts/test.sh'
//       }
//     }
//   }

//   post {
//     success {
//       echo "Build and test were completed successfully."
//     }
//     failure {
//       echo "Build and test process failed."
//     }
//   }
// }
pipeline {
  agent none
  options {
    disableConcurrentBuilds()
  }
  stages {
    stage('Build and Test') {
      agent {
        dockerfile {
          filename 'ci/Dockerfile'
          dir '.'
          label 'linux'
        }
      }
      environment {
        HOME = "${WORKSPACE}"
        MUNDY_DEPS = "${WORKSPACE}/mundy_deps"
        MUNDY_INSTALL = "${WORKSPACE}/mundy_install"
        SPACK_ROOT = "/opt/spack"
        SPACK_TRILINOS = "/root/spack_trilinos"
      }
      steps {
        sh '. ${SPACK_ROOT}/share/spack/setup-env.sh'
        sh 'spack env activate ${SPACK_TRILINOS}'
        sh 'mkdir -p ${MUNDY_DEPS}'
        sh 'dep/install_fmt.sh ${MUNDY_DEPS}'
        sh 'dep/install_gtest.sh ${MUNDY_DEPS}'
        sh 'dep/install_openrand.sh ${MUNDY_DEPS}'
        sh 'export TRILINOS_ROOT_DIR=$(spack location -i trilinos)'
        sh 'cmake -B build . \
            -DCMAKE_BUILD_TYPE=RELEASE \
            -DCMAKE_CXX_COMPILER=mpicxx \
            -DCMAKE_CXX_FLAGS="-O3 -g -fno-omit-frame-pointer -march=native" \
            -DCMAKE_INSTALL_PREFIX=${MUNDY_INSTALL} \
            -DTPL_ENABLE_MPI=ON \
            -DKokkos_ENABLE_SERIAL=OFF \
            -DKokkos_ENABLE_OPENMP=ON \
            -DKokkos_ENABLE_CUDA=OFF \
            -DMundy_ENABLE_MundyCore=ON \
            -DMundy_ENABLE_MundyMath=ON \
            -DMundy_ENABLE_MundyMesh=ON \
            -DMundy_ENABLE_MundyGeom=ON \
            -DMundy_ENABLE_MundyMeta=ON \
            -DMundy_ENABLE_MundyAgents=ON \
            -DMundy_ENABLE_MundyShapes=ON \
            -DMundy_ENABLE_MundyLinkers=ON \
            -DMundy_ENABLE_MundyIo=ON \
            -DMundy_ENABLE_MundyConstraints=ON \
            -DMundy_ENABLE_MundyBalance=OFF \
            -DMundy_ENABLE_MundyMotion=OFF \
            -DMundy_ENABLE_MundyAlens=ON \
            -DMundy_ENABLE_MundyDriver=OFF \
            -DMundy_ENABLE_TESTS=ON \
            -DMundy_ENABLE_GTest=ON \
            -DMundy_ENABLE_STKFMM=OFF \
            -DMundy_ENABLE_PVFMM=OFF \
            -DMundy_TEST_CATEGORIES="BASIC;CONTINUOUS;NIGHTLY;HEAVY;PERFORMANCE" \
            -DTPL_GTest_DIR:PATH=${MUNDY_DEPS} \
            -DTPL_OpenRAND_DIR:PATH=${MUNDY_DEPS} \
            -DTPL_fmt_DIR:PATH=${MUNDY_DEPS} \
            -DTPL_Kokkos_DIR:PATH=${TRILINOS_ROOT_DIR} \
            -DTPL_KokkosKernels_DIR:PATH=${TRILINOS_ROOT_DIR} \
            -DTPL_STK_DIR:PATH=${TRILINOS_ROOT_DIR} \
            -DTPL_Teuchos_DIR:PATH=${TRILINOS_ROOT_DIR} \
            ${ccache_args} \
            ${compiler_flags} \
            ${install_dir} \
            ${extra_args}' 
      }
    }
  }
}
