def cleanCheckout() {
  // noop - do nothing
  echo 'cleanCheckout() called - not yet implemented'
}

// pipeline {
//   agent any

//   stages {
//     stage('Validate repo') {
//       agent {
//         dockerfile {
//           filename 'ci/Dockerfile' // Can also be relative path to Dockerfile
//           dir '.'
//           label 'linux'
//           /* args '-X -Y' // These get passed to docker run */
//           /* additionalBuildArgs '-X -Y' // These get passed to docker build */
//         }
//       }
//       steps {
//         script {
//           cleanCheckout()
//         }
//       }
//       post { always { sh "rm -rf ./*" }}
//     }

//     stage('Build Software and Test Via Docker') {
//       agent {
//         dockerfile {
//           filename 'ci/Dockerfile' // Can also be relative path to Dockerfile
//           dir '.'
//           label 'linux'
//           /* args '-X -Y' // These get passed to docker run */
//           /* additionalBuildArgs '-X -Y' // These get passed to docker build */
//         }
//       }
//       steps {
//         echo 'Building software inside the container'
//         sh './scripts/build.sh'

//         echo 'Executing tests'
//         sh './scripts/test.sh'
//       }
//     }
//   }

//   post {
//     success {
//       echo "Build and test were completed successfully."
//     }
//     failure {
//       echo "Build and test process failed."
//     }
//   }
// }
pipeline {
  agent none
  options {
    disableConcurrentBuilds()
  }
  stages {
    stage('Build and Test') {
      agent {
        dockerfile {
          filename 'ci/Dockerfile'
          dir '.'
          label 'linux'
        }
      }
      environment {
        HOME = "${WORKSPACE}"
        MUNDY_DEPS = "${WORKSPACE}/mundy_deps"
        SPACK_ROOT = "/opt/spack"
        SPACK_TRILINOS = "/root/spack_trilinos"
      }
      steps {
        sh '. ${SPACK_ROOT}/share/spack/setup-env.sh'
        sh 'dep/install_fmt.sh ${MUNDY_DEPS}'
        sh 'dep/install_gtest.sh ${MUNDY_DEPS}'
        sh 'ls ${MUNDY_DEPS}'
      }
    }
  }
}
